# CMake generated Testfile for 
# Source directory: /home/wangmaosen/copy_linux/third/KVStore/module/lstl
# Build directory: /home/wangmaosen/copy_linux/third/KVStore/build-netlemo/module/lstl
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(lstl.memory.test_alloc "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/memory/test_alloc")
set_tests_properties(lstl.memory.test_alloc PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;31;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.memory.test_construct "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/memory/test_construct")
set_tests_properties(lstl.memory.test_construct PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;31;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.memory.test_uninitialized "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/memory/test_uninitialized")
set_tests_properties(lstl.memory.test_uninitialized PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;31;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.memory.test_allocator "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/memory/test_allocator")
set_tests_properties(lstl.memory.test_allocator PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;31;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.memory.test_temporary_buffer "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/memory/test_temporary_buffer")
set_tests_properties(lstl.memory.test_temporary_buffer PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;31;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.memory.test_type_traits "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/memory/test_type_traits")
set_tests_properties(lstl.memory.test_type_traits PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;31;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.memory.test_oom_policy "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/memory/test_oom_policy")
set_tests_properties(lstl.memory.test_oom_policy PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;31;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.memory.test_pool_single "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/memory/test_pool_single")
set_tests_properties(lstl.memory.test_pool_single PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;31;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.memory.test_algorithm "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/memory/test_algorithm")
set_tests_properties(lstl.memory.test_algorithm PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;31;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.memory.test_memory_stress "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/memory/test_memory_stress")
set_tests_properties(lstl.memory.test_memory_stress PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;31;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.container.test_vector "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/container/test_vector")
set_tests_properties(lstl.container.test_vector PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;37;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.container.test_list "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/container/test_list")
set_tests_properties(lstl.container.test_list PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;37;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.container.test_deque "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/container/test_deque")
set_tests_properties(lstl.container.test_deque PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;37;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.container.test_slist "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/container/test_slist")
set_tests_properties(lstl.container.test_slist PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;37;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.container.test_heap "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/container/test_heap")
set_tests_properties(lstl.container.test_heap PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;37;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.container.test_adapter "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/container/test_adapter")
set_tests_properties(lstl.container.test_adapter PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;37;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.container.test_associative "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/container/test_associative")
set_tests_properties(lstl.container.test_associative PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;37;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.container.test_b_associative "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/container/test_b_associative")
set_tests_properties(lstl.container.test_b_associative PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;37;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
add_test(lstl.container.test_skip_associative "/home/wangmaosen/copy_linux/third/KVStore/bin/lstl/container/test_skip_associative")
set_tests_properties(lstl.container.test_skip_associative PROPERTIES  _BACKTRACE_TRIPLES "/home/wangmaosen/copy_linux/third/KVStore/cmake/KVStoreHelpers.cmake;62;add_test;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;37;kvstore_add_tests;/home/wangmaosen/copy_linux/third/KVStore/module/lstl/CMakeLists.txt;0;")
