#include <gtest/gtest.h>
#include "ledis_helpers.h"
using namespace ledis; using namespace kvtest;
TEST(StorageSmokeTest, AllRegisteredCommands) {
  ensureCommandTable(); StorageEngine e;
  (void)runCommand(e, {"acl", "LIST"});
  (void)runCommand(e, {"append", "sk", "1"});
  (void)runCommand(e, {"bgsave"});
  (void)runCommand(e, {"bitcount", "sk"});
  (void)runCommand(e, {"bitop", "AND", "bd", "bk", "bk"});
  (void)runCommand(e, {"bitpos", "bk", "0"});
  (void)runCommand(e, {"bzpopmax", "zk", "1"});
  (void)runCommand(e, {"bzpopmin", "zk", "1"});
  (void)runCommand(e, {"client"});
  (void)runCommand(e, {"command"});
  (void)runCommand(e, {"config", "GET", "maxmemory"});
  (void)runCommand(e, {"copy", "sk", "sk2"});
  (void)runCommand(e, {"dbsize"});
  (void)runCommand(e, {"decr", "sk"});
  (void)runCommand(e, {"decrby", "sk", "1"});
  (void)runCommand(e, {"del", "sk"});
  (void)runCommand(e, {"eval", "k", "v"});
  (void)runCommand(e, {"evalsha", "k", "v"});
  (void)runCommand(e, {"exists", "sk"});
  (void)runCommand(e, {"expire", "sk", "9999999999"});
  (void)runCommand(e, {"expireat", "sk", "9999999999"});
  (void)runCommand(e, {"expiretime", "sk"});
  (void)runCommand(e, {"flushdb"});
  (void)runCommand(e, {"geoadd", "gk", "0", "0", "p"});
  (void)runCommand(e, {"geodist", "gk", "p"});
  (void)runCommand(e, {"geohash", "gk", "p"});
  (void)runCommand(e, {"geopos", "gk", "p"});
  (void)runCommand(e, {"georadius", "gk", "0", "0", "100", "km"});
  (void)runCommand(e, {"get", "sk"});
  (void)runCommand(e, {"getbit", "bk", "0"});
  (void)runCommand(e, {"getdel", "sk"});
  (void)runCommand(e, {"getrange", "sk", "1"});
  (void)runCommand(e, {"getset", "sk", "v"});
  (void)runCommand(e, {"hdel", "hk", "f"});
  (void)runCommand(e, {"hello"});
  (void)runCommand(e, {"hexists", "sk", "1"});
  (void)runCommand(e, {"hget", "sk", "1"});
  (void)runCommand(e, {"hgetall", "k", "v"});
  (void)runCommand(e, {"hincrby", "hk", "1"});
  (void)runCommand(e, {"hincrbyfloat", "hk", "1"});
  (void)runCommand(e, {"hkeys", "sk"});
  (void)runCommand(e, {"hlen", "sk"});
  (void)runCommand(e, {"hmget", "hk", "f"});
  (void)runCommand(e, {"hmset", "hk", "f"});
  (void)runCommand(e, {"hrandfield", "hk", "f"});
  (void)runCommand(e, {"hscan", "hk", "0"});
  (void)runCommand(e, {"hset", "hk", "f", "v"});
  (void)runCommand(e, {"hsetnx", "hk", "f", "v"});
  (void)runCommand(e, {"hstrlen", "sk", "1"});
  (void)runCommand(e, {"hvals", "sk"});
  (void)runCommand(e, {"incr", "sk"});
  (void)runCommand(e, {"incrby", "sk", "1"});
  (void)runCommand(e, {"incrbyfloat", "sk", "1"});
  (void)runCommand(e, {"info"});
  (void)runCommand(e, {"keys", "*"});
  (void)runCommand(e, {"lindex", "sk", "1"});
  (void)runCommand(e, {"llen", "sk"});
  (void)runCommand(e, {"lmove", "lk", "lk2", "LEFT", "RIGHT"});
  (void)runCommand(e, {"lpop", "sk"});
  (void)runCommand(e, {"lpos", "sk", "1"});
  (void)runCommand(e, {"lpush", "lk", "a"});
  (void)runCommand(e, {"lrange", "lk", "0", "-1"});
  (void)runCommand(e, {"lrem", "lk", "0", "v"});
  (void)runCommand(e, {"lset", "lk", "0", "v"});
  (void)runCommand(e, {"ltrim", "lk", "0", "-1"});
  (void)runCommand(e, {"memory"});
  (void)runCommand(e, {"mget", "mk1", "v1", "mk2", "v2"});
  (void)runCommand(e, {"monitor"});
  (void)runCommand(e, {"mset", "mk1", "v1", "mk2", "v2"});
  (void)runCommand(e, {"msetnx", "mk1", "v1", "mk2", "v2"});
  (void)runCommand(e, {"object", "ENCODING", "sk"});
  (void)runCommand(e, {"persist", "sk"});
  (void)runCommand(e, {"pexpire", "sk", "9999999999"});
  (void)runCommand(e, {"pexpireat", "sk", "9999999999"});
  (void)runCommand(e, {"pexpiretime", "sk"});
  (void)runCommand(e, {"pfadd", "lk", "a"});
  (void)runCommand(e, {"pfcount", "sk"});
  (void)runCommand(e, {"pfmerge", "hllout", "hll1"});
  (void)runCommand(e, {"psetex", "sk", "60", "v"});
  (void)runCommand(e, {"psubscribe", "ch"});
  (void)runCommand(e, {"pttl", "sk"});
  (void)runCommand(e, {"publish", "ch", "msg"});
  (void)runCommand(e, {"pubsub"});
  (void)runCommand(e, {"punsubscribe", "ch"});
  (void)runCommand(e, {"randomkey"});
  (void)runCommand(e, {"rename", "sk", "sk2"});
  (void)runCommand(e, {"renamenx", "sk", "sk2"});
  (void)runCommand(e, {"restore", "rk", "0", "payload"});
  (void)runCommand(e, {"rpop", "sk"});
  (void)runCommand(e, {"rpush", "lk", "a"});
  (void)runCommand(e, {"sadd", "lk", "a"});
  (void)runCommand(e, {"save"});
  (void)runCommand(e, {"scan", "0"});
  (void)runCommand(e, {"scard", "sk"});
  (void)runCommand(e, {"script", "k", "v"});
  (void)runCommand(e, {"sdiff", "2", "zk", "zk2"});
  (void)runCommand(e, {"sdiffstore", "out", "2", "zk", "zk2"});
  (void)runCommand(e, {"select"});
  (void)runCommand(e, {"set", "sk", "v"});
  (void)runCommand(e, {"setbit", "bk", "0", "1"});
  (void)runCommand(e, {"setex", "sk", "60", "v"});
  (void)runCommand(e, {"setnx", "sk", "v"});
  (void)runCommand(e, {"setrange", "k", "v"});
  (void)runCommand(e, {"shutdown"});
  (void)runCommand(e, {"sinter", "2", "zk", "zk2"});
  (void)runCommand(e, {"sinterstore", "out", "2", "zk", "zk2"});
  (void)runCommand(e, {"sismember", "sk", "1"});
  (void)runCommand(e, {"slowlog"});
  (void)runCommand(e, {"smembers", "sk"});
  (void)runCommand(e, {"smismember", "hk", "f"});
  (void)runCommand(e, {"smove", "sk", "sk2"});
  (void)runCommand(e, {"sort", "lk"});
  (void)runCommand(e, {"spop", "sk"});
  (void)runCommand(e, {"srandmember", "hk", "f"});
  (void)runCommand(e, {"srem", "hk", "f"});
  (void)runCommand(e, {"sscan", "hk", "0"});
  (void)runCommand(e, {"strlen", "sk"});
  (void)runCommand(e, {"subscribe", "ch"});
  (void)runCommand(e, {"sunion", "2", "zk", "zk2"});
  (void)runCommand(e, {"sunionstore", "out", "2", "zk", "zk2"});
  (void)runCommand(e, {"time"});
  (void)runCommand(e, {"touch", "sk"});
  (void)runCommand(e, {"ttl", "sk"});
  (void)runCommand(e, {"type", "sk"});
  (void)runCommand(e, {"unsubscribe", "ch"});
  (void)runCommand(e, {"xack", "xk", "0-0"});
  (void)runCommand(e, {"xadd", "xk", "*", "f", "v"});
  (void)runCommand(e, {"xdel", "xk", "0-0"});
  (void)runCommand(e, {"xgroup", "CREATE", "xk", "g", "0"});
  (void)runCommand(e, {"xlen", "sk"});
  (void)runCommand(e, {"xpending", "xk", "0-0"});
  (void)runCommand(e, {"xrange", "xk", "0-0"});
  (void)runCommand(e, {"xread", "xk", "0-0"});
  (void)runCommand(e, {"xreadgroup", "k", "v"});
  (void)runCommand(e, {"zadd", "zk", "1", "m"});
  (void)runCommand(e, {"zcard", "sk"});
  (void)runCommand(e, {"zcount", "lk", "0", "-1"});
  (void)runCommand(e, {"zdiff", "2", "zk", "zk2"});
  (void)runCommand(e, {"zdiffstore", "out", "2", "zk", "zk2"});
  (void)runCommand(e, {"zincrby", "zk", "1", "m"});
  (void)runCommand(e, {"zinter", "2", "zk", "zk2"});
  (void)runCommand(e, {"zinterstore", "out", "2", "zk", "zk2"});
  (void)runCommand(e, {"zlexcount", "lk", "0", "-1"});
  (void)runCommand(e, {"zpopmax", "zk", "1"});
  (void)runCommand(e, {"zpopmin", "zk", "1"});
  (void)runCommand(e, {"zrandmember", "zk", "1"});
  (void)runCommand(e, {"zrange", "lk", "0", "-1"});
  (void)runCommand(e, {"zrangebylex", "lk", "0", "-1"});
  (void)runCommand(e, {"zrangebyscore", "lk", "0", "-1"});
  (void)runCommand(e, {"zrank", "sk", "1"});
  (void)runCommand(e, {"zrem", "hk", "f"});
  (void)runCommand(e, {"zremrangebylex", "lk", "0", "-1"});
  (void)runCommand(e, {"zremrangebyrank", "lk", "0", "-1"});
  (void)runCommand(e, {"zremrangebyscore", "lk", "0", "-1"});
  (void)runCommand(e, {"zrevrange", "lk", "0", "-1"});
  (void)runCommand(e, {"zrevrangebyscore", "lk", "0", "-1"});
  (void)runCommand(e, {"zrevrank", "sk", "1"});
  (void)runCommand(e, {"zscan", "hk", "0"});
  (void)runCommand(e, {"zscore", "sk", "1"});
  (void)runCommand(e, {"zunion", "2", "zk", "zk2"});
  (void)runCommand(e, {"zunionstore", "out", "2", "zk", "zk2"});
}
