# CMake generated Testfile for 
# Source directory: /home/wangmaosen/app/cpp/KVStore/tests/lstl
# Build directory: /home/wangmaosen/app/cpp/KVStore/build-stress/tests/lstl
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_lstl_vector "/home/wangmaosen/app/cpp/KVStore/bin/test_lstl_vector")
set_tests_properties(test_lstl_vector PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wangmaosen/app/cpp/KVStore/tests/CMakeLists.txt;26;add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;1;kvstore_add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;0;")
add_test(test_lstl_list "/home/wangmaosen/app/cpp/KVStore/bin/test_lstl_list")
set_tests_properties(test_lstl_list PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wangmaosen/app/cpp/KVStore/tests/CMakeLists.txt;26;add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;2;kvstore_add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;0;")
add_test(test_lstl_deque "/home/wangmaosen/app/cpp/KVStore/bin/test_lstl_deque")
set_tests_properties(test_lstl_deque PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wangmaosen/app/cpp/KVStore/tests/CMakeLists.txt;26;add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;3;kvstore_add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;0;")
add_test(test_lstl_map_set "/home/wangmaosen/app/cpp/KVStore/bin/test_lstl_map_set")
set_tests_properties(test_lstl_map_set PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wangmaosen/app/cpp/KVStore/tests/CMakeLists.txt;26;add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;4;kvstore_add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;0;")
add_test(test_lstl_unordered "/home/wangmaosen/app/cpp/KVStore/bin/test_lstl_unordered")
set_tests_properties(test_lstl_unordered PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wangmaosen/app/cpp/KVStore/tests/CMakeLists.txt;26;add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;5;kvstore_add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;0;")
add_test(test_lstl_stack_queue "/home/wangmaosen/app/cpp/KVStore/bin/test_lstl_stack_queue")
set_tests_properties(test_lstl_stack_queue PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wangmaosen/app/cpp/KVStore/tests/CMakeLists.txt;26;add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;6;kvstore_add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;0;")
add_test(test_lstl_alloc "/home/wangmaosen/app/cpp/KVStore/bin/test_lstl_alloc")
set_tests_properties(test_lstl_alloc PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wangmaosen/app/cpp/KVStore/tests/CMakeLists.txt;26;add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;7;kvstore_add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;0;")
add_test(test_lstl_slist "/home/wangmaosen/app/cpp/KVStore/bin/test_lstl_slist")
set_tests_properties(test_lstl_slist PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wangmaosen/app/cpp/KVStore/tests/CMakeLists.txt;26;add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;8;kvstore_add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;0;")
add_test(test_lstl_skip "/home/wangmaosen/app/cpp/KVStore/bin/test_lstl_skip")
set_tests_properties(test_lstl_skip PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wangmaosen/app/cpp/KVStore/tests/CMakeLists.txt;26;add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;9;kvstore_add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;0;")
add_test(test_lstl_bplus "/home/wangmaosen/app/cpp/KVStore/bin/test_lstl_bplus")
set_tests_properties(test_lstl_bplus PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wangmaosen/app/cpp/KVStore/tests/CMakeLists.txt;26;add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;10;kvstore_add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;0;")
add_test(test_lstl_type_traits "/home/wangmaosen/app/cpp/KVStore/bin/test_lstl_type_traits")
set_tests_properties(test_lstl_type_traits PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wangmaosen/app/cpp/KVStore/tests/CMakeLists.txt;26;add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;11;kvstore_add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;0;")
add_test(test_lstl_construct "/home/wangmaosen/app/cpp/KVStore/bin/test_lstl_construct")
set_tests_properties(test_lstl_construct PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wangmaosen/app/cpp/KVStore/tests/CMakeLists.txt;26;add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;12;kvstore_add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;0;")
add_test(test_lstl_extended "/home/wangmaosen/app/cpp/KVStore/bin/test_lstl_extended")
set_tests_properties(test_lstl_extended PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wangmaosen/app/cpp/KVStore/tests/CMakeLists.txt;26;add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;13;kvstore_add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;0;")
add_test(test_lstl_comprehensive "/home/wangmaosen/app/cpp/KVStore/bin/test_lstl_comprehensive")
set_tests_properties(test_lstl_comprehensive PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wangmaosen/app/cpp/KVStore/tests/CMakeLists.txt;26;add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;14;kvstore_add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;0;")
add_test(test_lstl_exhaustive "/home/wangmaosen/app/cpp/KVStore/bin/test_lstl_exhaustive")
set_tests_properties(test_lstl_exhaustive PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wangmaosen/app/cpp/KVStore/tests/CMakeLists.txt;26;add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;15;kvstore_add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;0;")
add_test(test_lstl_boundary_fault "/home/wangmaosen/app/cpp/KVStore/bin/test_lstl_boundary_fault")
set_tests_properties(test_lstl_boundary_fault PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wangmaosen/app/cpp/KVStore/tests/CMakeLists.txt;26;add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;16;kvstore_add_test;/home/wangmaosen/app/cpp/KVStore/tests/lstl/CMakeLists.txt;0;")
