worker_processes 4;
worker_rlimit_nofile 65535;
error_log /dev/null crit;
pid /tmp/nginx_echo.pid;

events {
    worker_connections 8192;
    multi_accept on;
}

http {
    access_log off;
    keepalive_timeout 75;
    keepalive_requests 1000000;
    sendfile on;
    tcp_nopush on;

    server {
        listen 19003;
        server_name localhost;

        location /ping {
            return 200 'ok';
        }

        location /echo {
            lua_need_request_body on;
            content_by_lua_block {
                ngx.req.read_body()
                local body = ngx.req.get_body_data()
                if body and #body > 0 then
                    ngx.header["Content-Type"] = "application/octet-stream"
                    ngx.print(body)
                else
                    ngx.status = 400
                end
            }
        }
    }
}
